markdown: kramdown

repository-url: https://github.com/NICMx/RedDog

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      category: "Documentation"

